### ISSUE TITLE
Boundary conditions using mesh properties.

### ISSUE THREAD

**Issue by wilko339** [deepmodeling/jax-fem#20]
When defining boundary conditions for nodes, is there a way the interface can be extended to not only take in the node coordinates, but also the node index? Something like this:

```
def top_nodes(point, index):
    top = jnp.isclose(point[2], upper_surface_height, atol=TOLERANCE    # Nodes on the top surface of my mesh
    active = jnp.any(jnp.in1d(point.index, active_nodes))    # Nodes in my predefined active list
    return top & active
```

I am implementing a layer-by-layer model with element activation. I can deactivate elements above a certain height based on their centroid, but when applying the boundary condition, I cannot select only the nodes connected to my active elements with the XYZ position alone. 

Any suggestions welcome!

**Comment by tianjuxue** [comment]
Are you imposing Dirichlet boundary condition or Neumann condition?

**Comment by wilko339** [comment]
Neumann, an input heat flux.
