### ISSUE TITLE
Remove from jax.config import config, from fe.py

### ISSUE THREAD

**Issue by mmorier-etu** [deepmodeling/jax-fem#22]
Hello everyone, 
Is it possible to remove "from jax.config import config" from the files ?
I have to create a dockerfile with JAX-FEM, and it will not be working because of that.
It works well in a conda venv without "from jax.config import config", otherwise I get an error because of the update.
Thanks a lot

**Comment by tianjuxue** [comment]
I just removed it.

**Comment by caoliu0706** [comment]
I have tested that if you replace "from jax.config import config" by "from jax import config" in files fe.py, mma.py and solver.py, the calculation will be fine. [https://github.com/google/jax/discussions/18403](https://github.com/google/jax/discussions/18403)

**Comment by mmorier-etu** [comment]
> I have tested that if you replace "from jax.config import config" by "from jax import config" in files fe.py, mma.py and solver.py, the calculation will be fine. [google/jax#18403](https://github.com/google/jax/discussions/18403)

Yes thank you, it is just that I am using a container so I don't have access to this files that easily, but i'll try that

**Comment by tianjuxue** [comment]
The latest JAX-FEM source code has been updated to be compatible with JAX version 0.4.26, so that you should not see any error message of this kind. The [PyPI package jax-fem](https://pypi.org/project/jax-fem/) is also updated to reflect this change.

**Comment by mmorier-etu** [comment]
> The latest JAX-FEM source code has been updated to be compatible with JAX version 0.4.26, so that you should not see any error message of this kind. The [PyPI package jax-fem](https://pypi.org/project/jax-fem/) is also updated to reflect this change.

Ok thank you !
