### ISSUE TITLE
issue with petsc4py

### ISSUE THREAD

**Issue by karthikeaton** [deepmodeling/jax-fem#23]
I am trying to install the jax-fem on a windows platform. I am unable to install Petsc4py using pip install. I am not able to install using condo as well. It says package not found in the conda-forge channels. Is JAX-FEM not meant to work on windows? Please help as this package will be extremely useful for my research.

**Comment by tianjuxue** [comment]
JAX itself is not meant to be used on Windows. Same holds true for JAX-FEM. Please consider a linux system like Ubuntu or Mac OS will also be fine.

**Comment by kweonhj** [comment]
"ModuleNotFoundError: No module named 'petsc4py'
I am also unable to install petsc3py via pip.
Can you give a solution?"

**Comment by tianjuxue** [comment]
Please exactly follow the instruction to install JAX-FEM. `petsc4py` is known to have issue with pip. You can only use conda to install `petsc4py`.

**Comment by kweonhj** [comment]
Thank you for your prompt response! 
I tried creating a virtual environment as you suggested, but encountered the following error. Is there a solution to this?

`
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - petsc4py==3.20.0
  - fenics=2019.1.0*

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
`

**Comment by tianjuxue** [comment]
Are you using Windows? If so, please avoid using Windows. There is no support for Windows for JAX-FEM.

**Comment by kweonhj** [comment]
Thank you so much it works great with my mac
