### ISSUE TITLE
关于线性和非线性分析范围的问题

### ISSUE THREAD

**Issue by leedz0210** [deepmodeling/jax-fem#30]
你好，我是一个有限元新手，请问这个库能对刚性物体，生物材料，如骨头这类进行一个受力模拟分析吗

**Comment by tianjuxue** [comment]
刚体一般不采用有限元方法，但可以使用小变形假设，比如线弹性，在有限元框架下分析。

**Comment by leedz0210** [comment]
好的谢谢，您的这篇文章让我受益匪浅。
