### ISSUE TITLE
issue.example.py

### ISSUE THREAD

**Issue by leedz0210** [deepmodeling/jax-fem#32]
Hello, when running the example file, the following warning was generated. Is this normal? Could you please tell me what caused this and how I can solve it? I would be very grateful.
![屏幕截图 2024-09-09 160031](https://github.com/user-attachments/assets/47b6c5ad-5f4a-407c-b43d-3670d40a39e5)

**Comment by tianjuxue** [comment]
It is normal. You are solving a 2D problem, but VTU only supports 3D points, so appending with 0 is automatically done for the the 2D **points** to make them 3D. Sometimes you have trouble viewing the deformation of a 2D object in Paraview, and you need to append 0 manually for your **displacement solution**, like [here](https://github.com/deepmodeling/jax-fem/blob/main/demos/topology_optimization/example.py#L136).
