### ISSUE TITLE
How to add torsion?

### ISSUE THREAD

**Issue by hanfengzhang** [deepmodeling/jax-fem#34]
Hi all,

I am just curious about how to add torsion to the simulation of JAX-FEM. I was trying to go over the demos and applications but might miss something important. So could you please let me know if there is an example for torsion or how to implement torsion, e.g., on the linear elastic beam?

**Comment by xwpken** [comment]
Currently, for solid mechanics, JAX-FEM only support planar and solid elements, which only has dofs of displacement. Elements with rotation dofs, e.g., beam, shell, plate,  are not supported. You may try to assign the distributed forces equivalent to the effect of torsion to perform the simulation.
